# Generated by Django 4.2.3 on 2023-07-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('nome_responsavel', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('quantidade_ptc', models.IntegerField(max_length=20)),
                ('data_inicio', models.DateField(max_length=10)),
                ('data_encerramento', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField(max_length=10)),
            ],
        ),
    ]
