# Generated by Django 4.2.3 on 2023-08-14 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('nome_responsavel', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('quantidade_ptc', models.IntegerField()),
                ('data_inicio', models.DateField(max_length=10)),
                ('data_encerramento', models.DateField(max_length=10)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.local')),
            ],
        ),
    ]
