# Generated by Django 4.2.3 on 2023-11-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='nome_responsavel',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='atividade',
            name='arquivos',
            field=models.FileField(default=1, upload_to='arquivos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_encerramento',
            field=models.DateField(verbose_name='Data de encerramento'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_inicio',
            field=models.DateField(blank=True, verbose_name='Data de inicio'),
        ),
    ]
