# Generated by Django 4.2.3 on 2023-08-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='nome_responsavel',
            new_name='usuario',
        ),
    ]
