# Generated by Django 4.2.3 on 2023-12-05 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='nome_responsavel',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='atividade',
            name='data_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='atividade',
            name='duracao',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_encerramento',
            field=models.DateField(verbose_name='Data de encerramento'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de inicio'),
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivos/')),
                ('Atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivo', to='core.atividade')),
            ],
        ),
    ]
