# Generated by Django 4.2.3 on 2023-08-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nome_responsavel_atividade_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='arquivos',
            field=models.FileField(default=1, upload_to='arquivos/'),
            preserve_default=False,
        ),
    ]
