# Generated by Django 4.2.3 on 2023-07-29 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_atividade_quantidade_ptc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='imagem',
            field=models.ImageField(default='default_image.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='atividade',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.local'),
            preserve_default=False,
        ),
    ]
