# Generated by Django 4.2.3 on 2023-09-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_atividade_arquivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_encerramento',
            field=models.DateField(verbose_name='Data de encerramento'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_inicio',
            field=models.DateField(blank=True, verbose_name='Data de inicio'),
        ),
    ]
