# Generated by Django 4.2.3 on 2023-07-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_local_atividade_imagem_atividade_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
