# Generated by Django 4.2.3 on 2023-11-23 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='duracao',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AtividadeArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='arquivos/', verbose_name='Arquivos')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.atividade')),
            ],
        ),
    ]
