# Generated by Django 4.2.3 on 2023-09-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pdfmodel_alter_atividade_data_encerramento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='arquivos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='arquivos',
        ),
        migrations.AddField(
            model_name='atividade',
            name='arquivos',
            field=models.ManyToManyField(blank=True, to='core.file'),
        ),
    ]
