# Generated by Django 4.2.3 on 2023-08-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_atividade_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='imagem',
        ),
        migrations.AddField(
            model_name='atividade',
            name='arquivo',
            field=models.FileField(default=1, upload_to='arquivos/'),
            preserve_default=False,
        ),
    ]
