# Generated by Django 4.2.3 on 2023-08-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_atividade_imagem_atividade_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='arquivo',
        ),
    ]
