# Generated by Django 4.2.3 on 2023-09-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_file_remove_atividade_arquivos_atividade_arquivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='arquivos',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='atividade',
            name='arquivos',
            field=models.FileField(blank=True, upload_to='arquivos/'),
        ),
    ]
