# Generated by Django 4.2.3 on 2023-11-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_atividade_duracao_atividadearquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='duracao',
        ),
        migrations.DeleteModel(
            name='AtividadeArquivo',
        ),
    ]
