# Generated by Django 4.2.3 on 2023-08-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_atividade_arquivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
