# Generated by Django 4.2.3 on 2023-11-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_atividade_arquivos_atividade_duracao_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivo',
            old_name='file',
            new_name='Arquivo',
        ),
    ]
