# Generated by Django 4.2.3 on 2023-11-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_file_arquivo_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='Arquivo',
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='atividade',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='Atividade',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.atividade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(default=1, upload_to='arquivos/'),
            preserve_default=False,
        ),
    ]
