# Generated by Django 4.2.3 on 2023-09-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_anexos_atividade_remove_atividade_arquivos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anexos',
        ),
    ]
