# Generated by Django 4.2.3 on 2023-09-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_anexos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexos', models.FileField(upload_to='pdfs/', verbose_name='Arquivos')),
                ('arquivos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.atividade')),
            ],
        ),
    ]
