# Generated by Django 4.2.3 on 2023-11-27 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_arquivo_arquivo_remove_arquivo_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='Atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivo', to='core.atividade'),
        ),
    ]
