# Generated by Django 4.2.3 on 2023-11-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_arquivo_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_1', models.DateField()),
                ('date_1', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de inicio'),
        ),
    ]
