# Generated by Django 4.2.3 on 2023-09-19 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_anexos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexos',
            name='anexos',
        ),
        migrations.AddField(
            model_name='anexos',
            name='atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.atividade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anexos',
            name='arquivos',
            field=models.FileField(upload_to=' arquivos/%d/%m/%y'),
        ),
    ]
