# Generated by Django 4.2.3 on 2023-09-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_anexos_anexos_anexos_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexos',
            name='arquivos',
            field=models.FileField(upload_to='uploads/arquivos/%d/%m/%y'),
        ),
    ]
