# Generated by Django 4.2.3 on 2023-11-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_testdata_alter_atividade_data_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdata',
            old_name='date_1',
            new_name='date_2',
        ),
    ]
