# Generated by Django 4.2.3 on 2023-09-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_anexos_arquivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexos',
            name='atividade',
        ),
        migrations.AddField(
            model_name='atividade',
            name='arquivos',
            field=models.ManyToManyField(to='core.anexos'),
        ),
    ]
