# Generated by Django 4.2.3 on 2023-11-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_date_1_testdata_date_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestData',
        ),
    ]
