# Generated by Django 4.2.3 on 2023-09-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_anexos_atividade_atividade_arquivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexos',
            name='arquivos',
            field=models.FileField(upload_to='arquivos/'),
        ),
    ]
