# Generated by Django 4.2.3 on 2023-09-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_anexos_arquivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='arquivos',
        ),
        migrations.DeleteModel(
            name='Anexos',
        ),
        migrations.AddField(
            model_name='atividade',
            name='arquivos',
            field=models.FileField(default=1, upload_to='arquivos/'),
            preserve_default=False,
        ),
    ]
