# Generated by Django 4.2.3 on 2023-12-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_atividade_data_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='data_registro',
        ),
    ]
