# Generated by Django 4.2.3 on 2023-09-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_atividade_arquivos_delete_anexos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='arquivos',
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.atividade')),
            ],
        ),
    ]
