# Generated by Django 4.2.3 on 2023-09-27 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_atividade_arquivos_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='image',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.atividade'),
        ),
    ]
