# Generated by Django 4.2.3 on 2023-12-01 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_atividade_data_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='data_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
