# Generated by Django 4.2.3 on 2023-09-28 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_arquivo_image_arquivo_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='duracao',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='uploads/arquivos/'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.atividade'),
            preserve_default=False,
        ),
    ]
