# Generated by Django 4.2.3 on 2023-09-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_arquivo_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='duracao',
        ),
        migrations.AddField(
            model_name='atividade',
            name='arquivos',
            field=models.FileField(default=1, upload_to='arquivos/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Arquivo',
        ),
    ]
